kind: PersistentVolume
apiVersion: v1
metadata:
  name: ethereum-volume
  labels:
    type: local
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/kubernetes/ethereum"
